In [5]:
from pathlib import Path
import pandas as pd

In [15]:
DMR_PATH = Path("/home/daffa/Work/2026/02-JSPP67/results/dmr_analysis/CpG/TAA_high_SBC10_vs_low_SBC11/")
DMR_RESULTS = DMR_PATH / Path("dmr_results_15.tsv")

In [16]:
df = pd.read_csv(DMR_RESULTS, sep='\t')

In [24]:
df

,chr,start,end,length,nCG,meanMethy1,meanMethy2,diff.Methy,areaStat
0,NC_012873.2,25695728,25696782,1055,91,0.015600,0.849388,-0.833788,-4210.981970
1,NC_012873.2,39934020,39935310,1291,79,0.013631,0.900061,-0.886430,-4166.125909
2,NC_012877.2,45716228,45716793,566,76,0.011704,0.856628,-0.844925,-3974.316624
3,NC_012878.2,24538513,24539237,725,64,0.027463,0.897744,-0.870280,-3655.658245
4,NC_012873.2,47809141,47810122,982,66,0.010649,0.917182,-0.906533,-3612.440821
...,...,...,...,...,...,...,...,...,...
724,NC_012871.2,69644975,69645187,213,9,0.018177,0.903910,-0.885734,-269.096782
725,NC_012874.2,2409423,2413756,4334,9,0.907442,0.024558,0.882885,263.609233
726,NC_012871.2,62410326,62411068,743,9,0.014926,0.943229,-0.928303,-258.242162
727,NC_012877.2,33606365,33606610,246,9,0.011702,0.898080,-0.886378,-256.868488
728,NC_012874.2,10904450,10904647,198,9,0.018572,0.890098,-0.871526,-255.540347

In [28]:
# filter df with diff.Methy < 0
df_filtered = df[df["diff.Methy"] < 0]
df_filtered = df_filtered[0:50]
df_filtered

,chr,start,end,length,nCG,meanMethy1,meanMethy2,diff.Methy,areaStat
0,NC_012873.2,25695728,25696782,1055,91,0.015600,0.849388,-0.833788,-4210.981970
1,NC_012873.2,39934020,39935310,1291,79,0.013631,0.900061,-0.886430,-4166.125909
2,NC_012877.2,45716228,45716793,566,76,0.011704,0.856628,-0.844925,-3974.316624
3,NC_012878.2,24538513,24539237,725,64,0.027463,0.897744,-0.870280,-3655.658245
4,NC_012873.2,47809141,47810122,982,66,0.010649,0.917182,-0.906533,-3612.440821
5,NC_012878.2,2379664,2380987,1324,75,0.039972,0.909468,-0.869496,-3579.646139
6,NC_012877.2,16008079,16008902,824,78,0.010542,0.851057,-0.840516,-3456.962695
7,NC_012879.2,18105604,18106197,594,70,0.012639,0.851280,-0.838641,-3455.060495
8,NC_012874.2,7982458,7983185,728,65,0.016879,0.888493,-0.871614,-3348.609131
9,NC_012874.2,57546086,57547325,1240,64,0.009591,0.903176,-0.893584,-3329.080483
11,NC_012874.2,656106,656765,660,71,0.011451,0.834612,-0.823161,-3210.478488
12,NC_012877.2,54235655,54236304,650,66,0.009494,0.854098,-0.844604,-3194.446826
13,NC_012871.2,65098576,65099203,628,52,0.009627,0.922539,-0.912912,-3165.523189
15,NC_012875.2,50188680,50189556,877,65,0.011758,0.883915,-0.872158,-3061.792562
16,NC_012876.2,4688681,4689431,751,67,0.020855,0.865576,-0.844721,-3047.895927
17,NC_012870.2,29336717,29337387,671,60,0.014399,0.866403,-0.852004,-2982.467348
18,NC_012871.2,29549268,29549873,606,58,0.008618,0.855118,-0.846500,-2970.517614
19,NC_012870.2,77148358,77149883,1526,70,0.011220,0.893824,-0.882604,-2960.476989
22,NC_012876.2,64944682,64945508,827,71,0.012666,0.838491,-0.825825,-2878.354271
23,NC_012871.2,15448815,15449407,593,60,0.018036,0.856438,-0.838403,-2782.634583
24,NC_012874.2,1852602,1853175,574,52,0.012843,0.879426,-0.866584,-2779.634136
26,NC_012877.2,44877550,44878091,542,58,0.019098,0.854255,-0.835157,-2745.046142
27,NC_012877.2,62542432,62542875,444,55,0.026664,0.871215,-0.844551,-2716.095883
28,NC_012871.2,12857683,12858315,633,49,0.014186,0.891831,-0.877646,-2698.295365
29,NC_012871.2,5672754,5673542,789,52,0.009642,0.880203,-0.870561,-2636.929421
33,NC_012875.2,50386339,50386799,461,51,0.012296,0.853267,-0.840971,-2579.182048
34,NC_012877.2,54444328,54444852,525,52,0.035072,0.892575,-0.857503,-2575.964758
36,NC_012875.2,52524159,52524971,813,48,0.023301,0.918733,-0.895432,-2560.020068
37,NC_012877.2,49310501,49311680,1180,61,0.021664,0.884880,-0.863216,-2549.644303
38,NC_012878.2,13390589,13391770,1182,60,0.013675,0.896560,-0.882884,-2530.403029
39,NC_012873.2,40268364,40269060,697,48,0.014441,0.895302,-0.880861,-2473.116703
40,NC_012872.2,70750113,70751059,947,55,0.011995,0.888688,-0.876693,-2471.924590
41,NC_012879.2,9624589,9625122,534,52,0.009763,0.850185,-0.840422,-2466.645746
42,NC_012876.2,63113231,63113857,627,48,0.011305,0.905652,-0.894347,-2460.176896
43,NC_012874.2,43272820,43273333,514,56,0.013421,0.842299,-0.828877,-2450.333155
44,NC_012870.2,24858843,24859354,512,53,0.013572,0.841576,-0.828003,-2445.832443
46,NC_012878.2,43544584,43545281,698,48,0.012658,0.897813,-0.885155,-2399.720785
47,NC_012879.2,46345034,46345611,578,44,0.014337,0.903088,-0.888751,-2398.180256
48,NC_012879.2,16107730,16108139,410,53,0.012623,0.811525,-0.798903,-2396.187246
49,NC_012877.2,54900581,54901037,457,49,0.009566,0.828746,-0.819179,-2371.216735
51,NC_012870.2,20441807,20442376,570,54,0.016424,0.855603,-0.839179,-2348.386753
52,NC_012871.2,52688309,52689292,984,51,0.013509,0.905863,-0.892354,-2336.985987
54,NC_012870.2,61880973,61881466,494,52,0.014486,0.833498,-0.819012,-2328.202662
57,NC_012870.2,27385273,27385962,690,53,0.012631,0.867978,-0.855347,-2317.812673
58,NC_012873.2,63861127,63861856,730,52,0.010692,0.848990,-0.838299,-2286.901485
61,NC_012878.2,52978001,52978652,652,49,0.018368,0.874644,-0.856276,-2187.893250
62,NC_012878.2,26983059,26983499,441,43,0.010434,0.870082,-0.859648,-2181.311609
65,NC_012877.2,18626611,18627109,499,42,0.011108,0.897959,-0.886851,-2154.892592
66,NC_012871.2,56435887,56436355,469,48,0.011268,0.827415,-0.816146,-2134.619063
69,NC_012870.2,30878909,30879498,590,47,0.010263,0.859136,-0.848872,-2109.084148

In [29]:
df_filtered.to_csv(DMR_PATH / "dmr_results_15_filtered.tsv", sep='\t', index=False)